# Project information
site_name: Archivio Digitale
site_description: Documentazione dell'Archivio Digitale.
site_author: Riccardo Sangiorgio
site_url: https://itisenricofermi.github.io/archivio-digitale-docs/

# Repository
repo_name: ITISEnricoFermi/archivio-digitale-docs
repo_url: https://github.com/ITISEnricoFermi/archivio-digitale-docs

# Copyright
copyright: Copyright &copy; 2019 ITIS Enrico Fermi

# Configuration
theme:
  name: null
  custom_dir: mkdocs-material/material
  language: it
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.svg
  feature:
    tabs: true
nav:
    - Home: index.md
    - Dashboard: dashboard/index.md
    - Documenti:
        - Crea documenti: documents/create.md
        - Cerca documenti: documents/search.md
        - Trasferisci documenti: documents/transfer.md
    - Collezioni:
        - Crea collezioni: collections/create.md
        - Cerca collezioni: collections/search.md
    - Admin:
        - Richieste di iscrizione: admin/requests.md
        - Invia email: admin/sendmail.md
        - Entit√†: admin/entities.md
        - Crea utente: admin/users.create.md
        - Cerca utenti: admin/users.search.md
    - Profilo: profile/index.md
    - Impostazioni:
        - Account: settings/account.md
        - Autenticazione: settings/authentication.md

# Customization
extra:
  manifest: manifest.webmanifest
  social:
    - type: github
      link: https://github.com/ITISEnricoFermi
    - type: hashtag
      link: https://archivio.itisfermi.edu.it

# Extensions
markdown_extensions:
    - fontawesome_markdown
